config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  scope module: 'authors' do
    resources :posts do
      resources :post_elements
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :post_elements
end

app/models/post_element.rb
class PostElement < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed']}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/post_elements_controller.rb
module Authors
  class PostElementsController < AuthorsController
    before_action :set_post
    before_action :set_post_element, only: %i[ update destroy ]
  
    # POST /post_elements or /post_elements.json
    def create
      @post_element = @post.post_elements.build(post_element_params)
  
      if @post_element.save
        notice = nil
      else
        notice = @post_element.errors.full_messages.join(". ") << "."
      end
        
      redirect_to edit_post_path(@post), notice: notice

    end
  
    # PATCH/PUT /post_elements/1
    def update
      if @post_element.update(post_element_params)
        redirect_to @post_element, notice: "Post element was successfully updated."
      else
        render :edit
      end
    end
  
    # DELETE /post_elements/1 or /post_elements/1.json
    def destroy
      @post_element.destroy
      respond_to do |format|
        format.html { redirect_to post_elements_url, notice: "Post element was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.

      def set_post
        @post = current_author.posts.find(params[:post_id])
      end

      def set_post_element
        @post_element = @post.post_elements.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_element_params
        params.require(:post_element).permit(:element_type, :content)
      end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[ edit update destroy ]
  
    # GET /posts or /posts.json
    def index
      @posts = current_author.posts
    end
  
    # GET /posts/new
    def new
      @post = current_author.posts.build
    end
  
    # GET /posts/1/edit
    def edit
      @paragraph = @post.post_elements.build(element_type: 'paragraph')
    end
  
    # POST /posts or /posts.json
    def create
      @post = current_author.posts.build(post_params)
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description)
      end
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_author!

    layout 'authors'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_elements_helper.rb
module PostElementsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
    <div class="col-md-3">
        <%= link_to 'Back', posts_path, class: 'btn btn-secondary mb-3' %>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Editar Post </h4>
                <%= render 'form', post: @post %>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="mb-3">
            <%= form_with(model: [@post, @paragraph]) do |form| %>
                <%= form.hidden_field :element_type, value: 'paragraph' %>
                <%= form.submit 'Paragraph', class: 'btn btn-primary' %>
            <% end %>
        </div>

        <% @post.post_elements.each do |post_element| %>
            <% if post_element.persisted? %>
                <%= form_with(model: [@post, post_element]) do |form| %>
                    <%= form.text_area :content %>
                    <%= form.submit 'Save', class: 'btn btn-primary' %>
                <% end %>
            <% end %>
        <% end %>

    </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4"> 
  <span>Posts</span>
  <%= link_to 'Novo', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do%>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title mb-1 text-dark"> <%= post.title %> </h5>
        <p class='text-secondary mb-0'> <%= post.description %> </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniblogMiner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog Imersão 42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body class="bg-light">

    <div class="container">
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    
    </div>

  </body>
</html>